/-
# Structural derivation of the trilinear slot identities

This module derives the two slot-differentiation identities used by
`TrilinearCancellationCore` from an abstract multiplier Leibniz rule and
weighted integration-by-parts laws.

The abstraction separates the exact algebra from the analytic realization:

* `multiplier` represents the bilinear Fourier multiplier;
* `pairing` represents integration against the spatial weight;
* `pairingPrime` represents integration against the derivative of the weight;
* `dx` and `dy` represent the Cartesian derivatives.

No Fourier transform, integral, Schwartz-space construction, or operator
estimate is claimed here.
-/

import DGBOZK.TrilinearCancellationCore

set_option autoImplicit false

namespace DGBOZK
namespace TrilinearDifferentiationCore

section StructuralIdentities

variable {R V : Type*} [CommRing R] [AddCommGroup V]

/-- The weighted trilinear functional generated by a bilinear multiplier. -/
abbrev weightedTrilinear
    (pairing : V → V → R)
    (multiplier : V → V → V) :
    V → V → V → R :=
  fun f g h => pairing (multiplier f g) h

/--
The sum of the three transverse slot derivatives vanishes.

This is derived from the transverse multiplier Leibniz rule, additivity of
the pairing in its first argument, and transverse integration by parts.
-/
theorem transverse_slot_identity
    {multiplier : V → V → V}
    {pairing : V → V → R}
    {dy : V → V}
    (hLeibniz :
      ∀ f g,
        dy (multiplier f g)
          =
        multiplier (dy f) g + multiplier f (dy g))
    (hPairAdd :
      ∀ u v h,
        pairing (u + v) h = pairing u h + pairing v h)
    (hParts :
      ∀ u h,
        pairing (dy u) h + pairing u (dy h) = 0)
    (f g h : V) :
    weightedTrilinear pairing multiplier (dy f) g h
        + weightedTrilinear pairing multiplier f (dy g) h
        + weightedTrilinear pairing multiplier f g (dy h)
      = 0 := by
  calc
    weightedTrilinear pairing multiplier (dy f) g h
          + weightedTrilinear pairing multiplier f (dy g) h
          + weightedTrilinear pairing multiplier f g (dy h)
        =
      pairing
          (multiplier (dy f) g + multiplier f (dy g))
          h
        + pairing (multiplier f g) (dy h) := by
            rw [hPairAdd]
    _ =
      pairing (dy (multiplier f g)) h
        + pairing (multiplier f g) (dy h) := by
          rw [hLeibniz]
    _ = 0 := hParts (multiplier f g) h

/--
The sum of the three longitudinal slot derivatives is the negative
weight-derivative functional.

The extra term is precisely the abstract form of differentiating the
spatial weight during integration by parts.
-/
theorem longitudinal_slot_identity
    {multiplier : V → V → V}
    {pairing pairingPrime : V → V → R}
    {dx : V → V}
    (hLeibniz :
      ∀ f g,
        dx (multiplier f g)
          =
        multiplier (dx f) g + multiplier f (dx g))
    (hPairAdd :
      ∀ u v h,
        pairing (u + v) h = pairing u h + pairing v h)
    (hParts :
      ∀ u h,
        pairing (dx u) h + pairing u (dx h)
          = -pairingPrime u h)
    (f g h : V) :
    weightedTrilinear pairing multiplier (dx f) g h
        + weightedTrilinear pairing multiplier f (dx g) h
        + weightedTrilinear pairing multiplier f g (dx h)
      =
    -weightedTrilinear pairingPrime multiplier f g h := by
  calc
    weightedTrilinear pairing multiplier (dx f) g h
          + weightedTrilinear pairing multiplier f (dx g) h
          + weightedTrilinear pairing multiplier f g (dx h)
        =
      pairing
          (multiplier (dx f) g + multiplier f (dx g))
          h
        + pairing (multiplier f g) (dx h) := by
            rw [hPairAdd]
    _ =
      pairing (dx (multiplier f g)) h
        + pairing (multiplier f g) (dx h) := by
          rw [hLeibniz]
    _ =
      -pairingPrime (multiplier f g) h :=
        hParts (multiplier f g) h
    _ =
      -weightedTrilinear pairingPrime multiplier f g h := by
        rfl

/--
Closure of the exact trilinear cancellation from the structural multiplier
and weighted-pairing laws.

Unlike `exact_trilinear_cancellation`, this theorem does not take either
slot-differentiation identity as a hypothesis: both are derived internally.
-/
theorem exact_trilinear_cancellation_from_structural_laws
    {multiplier : V → V → V}
    {pairing pairingPrime : V → V → R}
    {dx dy : V → V}
    (hLeibnizY :
      ∀ f g,
        dy (multiplier f g)
          =
        multiplier (dy f) g + multiplier f (dy g))
    (hLeibnizX :
      ∀ f g,
        dx (multiplier f g)
          =
        multiplier (dx f) g + multiplier f (dx g))
    (hPairAdd :
      ∀ u v h,
        pairing (u + v) h = pairing u h + pairing v h)
    (hPartsY :
      ∀ u h,
        pairing (dy u) h + pairing u (dy h) = 0)
    (hPartsX :
      ∀ u h,
        pairing (dx u) h + pairing u (dx h)
          = -pairingPrime u h)
    (hcomm :
      ∀ u, dy (dx u) = dx (dy u))
    (f g h : V) :
    2 * weightedTrilinear pairing multiplier
          (dy f) (dx (dy g)) h
        +
      (weightedTrilinear pairing multiplier
          (dx (dy (dy f))) g h
        + weightedTrilinear pairing multiplier
            f (dx (dy (dy g))) h
        + weightedTrilinear pairing multiplier
            f g (dx (dy (dy h))))
      =
    -2 * weightedTrilinear pairing multiplier
          (dy (dy f)) (dx g) h
      - weightedTrilinear pairing multiplier
          (dy (dy f)) g (dx h)
      + weightedTrilinear pairing multiplier
          (dx f) (dy g) (dy h)
      + weightedTrilinear pairing multiplier
          (dx (dy f)) g (dy h)
      - weightedTrilinear pairingPrime multiplier
          (dy (dy f)) g h
      + weightedTrilinear pairingPrime multiplier
          (dy f) g (dy h)
      + weightedTrilinear pairingPrime multiplier
          f (dy g) (dy h) := by
  apply
    DGBOZK.TrilinearCancellationCore.exact_trilinear_cancellation
  · intro u v w
    exact transverse_slot_identity
      (multiplier := multiplier)
      (pairing := pairing)
      hLeibnizY hPairAdd hPartsY u v w
  · intro u v w
    exact longitudinal_slot_identity
      (multiplier := multiplier)
      (pairing := pairing)
      (pairingPrime := pairingPrime)
      hLeibnizX hPairAdd hPartsX u v w
  · exact hcomm

end StructuralIdentities

end TrilinearDifferentiationCore
end DGBOZK
